### ISSUE TITLE
Display error execute curl -X POST

### ISSUE THREAD

**Issue by acastillo2015** [watson-developer-cloud/questions-with-classifier-ega#54]
I have problem when I run this command: 

curl -X POST -H "Content-Type: application/json" -d @questions-with-classifier-ega-war\target\classes/answers.json 
http://buscadorinteligente.mybluemix.net/api/v1/manage/answer

Display this error:
 Exception thrown by application class 'com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance:220'
javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException
at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance(LibertyJaxRsServerFactoryBean.java:220)
at [internal classes]
at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:38)
at com.ibm.ws.webcontainer.filter.FilterInstanceWra pper.doFilter(FilterInstanceWrapper.java:207)
at [internal classes]

**Comment by acastillo2015** [comment]
I ne

**Comment by acastillo2015** [comment]
I need assigned
