### ISSUE TITLE
Issue when try to run the application on local environment

### ISSUE THREAD

**Issue by DxiaoYang** [watson-developer-cloud/questions-with-classifier-ega#75]
Question Background: 
    As the requirement of customer,we need to do secondary development based on questions-with-classifier-ega to add some new functions.
    So the first step is to try to run and debug questions-with-classifier-ega on local environment.
    But when we configure and deploy the code on our local environment,get some error.
    So I will appreciate your support to resolve this issue.

Our configuration process as following:
    1.use git clone  to download [framework-ega] and [questions-with-classifier-ega] to local C:\EGA
    2.import the code into eclipse 
    3.run mvn install against framework-ega and questions-with-classifier-ega
    4.install [webSphere Application Server Liberty at localhost] to C:\Liberty
    5.configuration the server
        5.1  Copy the  [SQLDB] from C:\EGA\questions-with-classifier-ega\questions-with-classifier-        ega-test\target\liberty\wlp\usr\servers\defaultServer to C:\Liberty\usr\servers\defaultServer
        5.2  To config the NLS service, add a server.env in C:\Liberty\usr\servers\defaultServer 
        5.3  add database configuration in the [server.xml] for Liberty.

	<jdbcDriver id="derby-driver">
	    <library name="derby-lib">
		<fileset dir="C:/CodeInGit/iip/EGA/questions-with-classifier-ega/questions-with-classifier-ega-test/target/lib/derby" includes="derby.jar, derbyclient.jar"/>
	    </library>
	</jdbcDriver>
	<dataSource id="derby-db" jdbcDriverRef="derby-driver" jndiName="jdbc/questions-with-classifier-ega-db" transactional="true">
		
		<properties.derby.embedded createDatabase="create" databaseName="SQLDB"/>
	</dataSource>
   6.Deploy the questions-with-classifier-ega-war to local Liberty server.
   7.Then try to access from browser with http://localhost:9080/

Error occured in Eclipse console:

    Internal Exception: java.sql.SQLSyntaxErrorException: SEQUENCE 'SEQ_GEN_SEQUENCE' does not exist.
    Error Code: 20000
    Call: VALUES(NEXT VALUE FOR SEQ_GEN_SEQUENCE)
    Query: ValueReadQuery(sql="VALUES(NEXT VALUE FOR SEQ_GEN_SEQUENCE)")
    [ERROR   ] SRVE0777E: Exception thrown by application class 'org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage:116'
    java.lang.RuntimeException: org.apache.cxf.interceptor.Fault: 
    Internal Exception: java.sql.SQLSyntaxErrorException: SEQUENCE 'SEQ_GEN_SEQUENCE' does not exist.
    Error Code: 20000
    Call: VALUES(NEXT VALUE FOR SEQ_GEN_SEQUENCE)
    Query: ValueReadQuery(sql="VALUES(NEXT VALUE FOR SEQ_GEN_SEQUENCE)")
	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:116)
	at [internal classes]
	at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:38)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
	at [internal classes]
    Caused by: org.apache.cxf.interceptor.Fault: 
    Internal Exception: java.sql.SQLSyntaxErrorException: SEQUENCE 'SEQ_GEN_SEQUENCE' does not exist.
    Error Code: 20000
    Call: VALUES(NEXT VALUE FOR SEQ_GEN_SEQUENCE)
    Query: ValueReadQuery(sql="VALUES(NEXT VALUE FOR SEQ_GEN_SEQUENCE)")
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:163)
	... 4 more
    Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.0.WAS-v20150513-26196d2): org.eclipse.persistence.exceptions.DatabaseException
    Internal Exception: java.sql.SQLSyntaxErrorException: SEQUENCE 'SEQ_GEN_SEQUENCE' does not exist.
    Error Code: 20000

**Comment by tdalbo92** [comment]
I'll help if I can, but the main server developer for this EGA has left IBM.  I wrote the UI :) 

Without knowing too much about JPA, I did notice you mentioned you copied the wlp installation from `C:\EGA` and in your derby libs it mentions `C:/CodeInGit/iip/EGA/`.  

This link might help  http://stackoverflow.com/questions/8761448/jpa-table-sequence-does-not-exist

**Comment by DxiaoYang** [comment]
Did you know other guys who joined this team and develop this project?
What should we do can the application can run successfully on native environment?
Or do you know other right deploying process ?

**Comment by tdalbo92** [comment]
Unfortunately, as I said, I'm the only one left to maintain this project.

One avenue that might be worth investigating is using Eclipse to attach to the remote debugging port exposed by Liberty.  I've never successfully done this, but it should work.  I don't know the details, so you might have to search online for them.
